version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: haywire478/quizz-repo:latest
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/quizz-app-local
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=quizz-app-local
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
